/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsImportRouteImport } from './routes/settings/import'
import { Route as YearYearIndexRouteImport } from './routes/year/$year/index'
import { Route as ShareYearIndexRouteImport } from './routes/share/$year/index'
import { Route as YearYearTypeRouteImport } from './routes/year/$year/$type'
import { Route as ShareYearTypeRouteImport } from './routes/share/$year/$type'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: '/settings/import',
  path: '/settings/import',
  getParentRoute: () => rootRouteImport,
} as any)
const YearYearIndexRoute = YearYearIndexRouteImport.update({
  id: '/year/$year/',
  path: '/year/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareYearIndexRoute = ShareYearIndexRouteImport.update({
  id: '/share/$year/',
  path: '/share/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const YearYearTypeRoute = YearYearTypeRouteImport.update({
  id: '/year/$year/$type',
  path: '/year/$year/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareYearTypeRoute = ShareYearTypeRouteImport.update({
  id: '/share/$year/$type',
  path: '/share/$year/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings': typeof SettingsIndexRoute
  '/share/$year/$type': typeof ShareYearTypeRoute
  '/year/$year/$type': typeof YearYearTypeRoute
  '/share/$year': typeof ShareYearIndexRoute
  '/year/$year': typeof YearYearIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings': typeof SettingsIndexRoute
  '/share/$year/$type': typeof ShareYearTypeRoute
  '/year/$year/$type': typeof YearYearTypeRoute
  '/share/$year': typeof ShareYearIndexRoute
  '/year/$year': typeof YearYearIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/': typeof SettingsIndexRoute
  '/share/$year/$type': typeof ShareYearTypeRoute
  '/year/$year/$type': typeof YearYearTypeRoute
  '/share/$year/': typeof ShareYearIndexRoute
  '/year/$year/': typeof YearYearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings/import'
    | '/settings'
    | '/share/$year/$type'
    | '/year/$year/$type'
    | '/share/$year'
    | '/year/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings/import'
    | '/settings'
    | '/share/$year/$type'
    | '/year/$year/$type'
    | '/share/$year'
    | '/year/$year'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings/import'
    | '/settings/'
    | '/share/$year/$type'
    | '/year/$year/$type'
    | '/share/$year/'
    | '/year/$year/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsImportRoute: typeof SettingsImportRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ShareYearTypeRoute: typeof ShareYearTypeRoute
  YearYearTypeRoute: typeof YearYearTypeRoute
  ShareYearIndexRoute: typeof ShareYearIndexRoute
  YearYearIndexRoute: typeof YearYearIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/import': {
      id: '/settings/import'
      path: '/settings/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year/$year/': {
      id: '/year/$year/'
      path: '/year/$year'
      fullPath: '/year/$year'
      preLoaderRoute: typeof YearYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$year/': {
      id: '/share/$year/'
      path: '/share/$year'
      fullPath: '/share/$year'
      preLoaderRoute: typeof ShareYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year/$year/$type': {
      id: '/year/$year/$type'
      path: '/year/$year/$type'
      fullPath: '/year/$year/$type'
      preLoaderRoute: typeof YearYearTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$year/$type': {
      id: '/share/$year/$type'
      path: '/share/$year/$type'
      fullPath: '/share/$year/$type'
      preLoaderRoute: typeof ShareYearTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ShareYearTypeRoute: ShareYearTypeRoute,
  YearYearTypeRoute: YearYearTypeRoute,
  ShareYearIndexRoute: ShareYearIndexRoute,
  YearYearIndexRoute: YearYearIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
