/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareYearRouteImport } from './routes/share.$year'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as ShareYearTypeRouteImport } from './routes/share.$year.$type'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedYearYearRouteImport } from './routes/_authenticated/year.$year'
import { Route as AuthenticatedSettingsImportRouteImport } from './routes/_authenticated/settings.import'
import { Route as AuthenticatedYearYearTypeRouteImport } from './routes/_authenticated/year.$year.$type'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareYearRoute = ShareYearRouteImport.update({
  id: '/share/$year',
  path: '/share/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const ShareYearTypeRoute = ShareYearTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ShareYearRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYearYearRoute = AuthenticatedYearYearRouteImport.update({
  id: '/year/$year',
  path: '/year/$year',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsImportRoute =
  AuthenticatedSettingsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedYearYearTypeRoute =
  AuthenticatedYearYearTypeRouteImport.update({
    id: '/$type',
    path: '/$type',
    getParentRoute: () => AuthenticatedYearYearRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/api/cron': typeof ApiCronRoute
  '/share/$year': typeof ShareYearRouteWithChildren
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/year/$year': typeof AuthenticatedYearYearRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/$year/$type': typeof ShareYearTypeRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/year/$year/$type': typeof AuthenticatedYearYearTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/cron': typeof ApiCronRoute
  '/share/$year': typeof ShareYearRouteWithChildren
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/year/$year': typeof AuthenticatedYearYearRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/$year/$type': typeof ShareYearTypeRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/year/$year/$type': typeof AuthenticatedYearYearTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/api/cron': typeof ApiCronRoute
  '/share/$year': typeof ShareYearRouteWithChildren
  '/_authenticated/settings/import': typeof AuthenticatedSettingsImportRoute
  '/_authenticated/year/$year': typeof AuthenticatedYearYearRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/$year/$type': typeof ShareYearTypeRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/year/$year/$type': typeof AuthenticatedYearYearTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/api/cron'
    | '/share/$year'
    | '/settings/import'
    | '/year/$year'
    | '/api/auth/$'
    | '/share/$year/$type'
    | '/settings/'
    | '/year/$year/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/cron'
    | '/share/$year'
    | '/settings/import'
    | '/year/$year'
    | '/api/auth/$'
    | '/share/$year/$type'
    | '/settings'
    | '/year/$year/$type'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/api/cron'
    | '/share/$year'
    | '/_authenticated/settings/import'
    | '/_authenticated/year/$year'
    | '/api/auth/$'
    | '/share/$year/$type'
    | '/_authenticated/settings/'
    | '/_authenticated/year/$year/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCronRoute: typeof ApiCronRoute
  ShareYearRoute: typeof ShareYearRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$year': {
      id: '/share/$year'
      path: '/share/$year'
      fullPath: '/share/$year'
      preLoaderRoute: typeof ShareYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/share/$year/$type': {
      id: '/share/$year/$type'
      path: '/$type'
      fullPath: '/share/$year/$type'
      preLoaderRoute: typeof ShareYearTypeRouteImport
      parentRoute: typeof ShareYearRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/year/$year': {
      id: '/_authenticated/year/$year'
      path: '/year/$year'
      fullPath: '/year/$year'
      preLoaderRoute: typeof AuthenticatedYearYearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/import': {
      id: '/_authenticated/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AuthenticatedSettingsImportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/year/$year/$type': {
      id: '/_authenticated/year/$year/$type'
      path: '/$type'
      fullPath: '/year/$year/$type'
      preLoaderRoute: typeof AuthenticatedYearYearTypeRouteImport
      parentRoute: typeof AuthenticatedYearYearRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsImportRoute: typeof AuthenticatedSettingsImportRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsImportRoute: AuthenticatedSettingsImportRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedYearYearRouteChildren {
  AuthenticatedYearYearTypeRoute: typeof AuthenticatedYearYearTypeRoute
}

const AuthenticatedYearYearRouteChildren: AuthenticatedYearYearRouteChildren = {
  AuthenticatedYearYearTypeRoute: AuthenticatedYearYearTypeRoute,
}

const AuthenticatedYearYearRouteWithChildren =
  AuthenticatedYearYearRoute._addFileChildren(
    AuthenticatedYearYearRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedYearYearRoute: typeof AuthenticatedYearYearRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedYearYearRoute: AuthenticatedYearYearRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ShareYearRouteChildren {
  ShareYearTypeRoute: typeof ShareYearTypeRoute
}

const ShareYearRouteChildren: ShareYearRouteChildren = {
  ShareYearTypeRoute: ShareYearTypeRoute,
}

const ShareYearRouteWithChildren = ShareYearRoute._addFileChildren(
  ShareYearRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCronRoute: ApiCronRoute,
  ShareYearRoute: ShareYearRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
